In [1]:
import numpy as np

In [2]:
arr =np.array([23,45,12,67,34])

In [3]:
print(arr)

[23 45 12 67 34]


In [5]:
arr

array([23, 45, 12, 67, 34])

In [6]:
arr =np.array([23,45,12,67,34,23.67])

In [7]:
arr

array([23.  , 45.  , 12.  , 67.  , 34.  , 23.67])

In [9]:
type(arr)  #ndarray means n dimaintional array

numpy.ndarray

In [12]:
arr1 =np.array([23,45,12,67,34,23.67,'pune'])

In [13]:
arr1

array(['23', '45', '12', '67', '34', '23.67', 'pune'], dtype='<U32')

In [14]:
arr1[2]

'12'

In [16]:
%%timeit
arr1 =np.array([23,45,12,67,34,23.67,'pune'])

7.05 µs ± 361 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [17]:
arr.ndim

1

In [18]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [20]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
np.arange(2,21,2.5) #using float value

array([ 2. ,  4.5,  7. ,  9.5, 12. , 14.5, 17. , 19.5])

In [24]:
np.zeros(10)



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
#2d array

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [27]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
arr2.shape

(4, 3)

In [30]:
arr2.size

12

In [31]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
arr2.ndim

2

In [33]:
arr2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
arr2.shape

(4, 3)

In [35]:
arr2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arr2.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [41]:
arr2.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [45]:
arr2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [46]:
arr2.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [55]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [64]:
arr2[0:3,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [72]:
np.linalg.inv(arr3)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [74]:
arr2 @ arr3 #cost product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150],
       [138, 171, 204]])